run-build:
	docker build . $(options) -t day2

run-test:
	docker run --rm -it day2 pytest

run-datatypes:
	docker run --rm -it day2 python project_day2/datatypes.py

run-bmi:
	docker run --rm -it day2 project_day2python bmi.py